name: Bithumb Entry Signal (15m)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
      - name: Commit state (last alert)
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .state.json || true
          git commit -m "update state $(date -u +'%F %T')" || echo "no changes"
          git push
